### ISSUE TITLE
Strange drift while the camera was sitting on the table - What might be the reason?

### ISSUE THREAD

**Issue by canberkgurel** [rbonghi/isaac_ros_tutorial#9]
Hi Raffaello, First, thanks for making this tutorial available, it's really helpful.

I have a question about the performance of Elbrus. I managed to build the dockerfile, and run it. 
[terminal_output_of_running_realsense_image.txt](https://github.com/rbonghi/isaac_ros_tutorial/files/8156027/terminal_output_of_running_realsense_image.txt)

I don't currently have a host machine where I can run rviz2 to visualize the camera but I am able to print odometry data on the terminal. I ssh'd into my Jetson and attached another terminal to the docker image with `docker exec -it <docker name> /bin/bash`

Then, I accessed the odometry data by `ros2 topic echo /camera/visual_odometry/tf_stamped` command. 

```
header:
  stamp:
    sec: 1646075980
    nanosec: 805066752
  frame_id: camera_infra1_optical_frame
child_frame_id: camera_infra1_optical_frame
rectified_transform:
  translation:
    x: 5.067627429962158
    y: 0.5380121469497681
    z: 0.25905224680900574
  rotation:
    x: 0.08346484038717318
    y: 0.09155384207216172
    z: 0.9584881184149462
    w: 0.25681127235414314
smooth_transform:
  translation:
    x: 5.067627429962158
    y: 0.5380121469497681
    z: 0.25905224680900574
  rotation:
    x: 0.08346484038717318
    y: 0.09155384207216172
    z: 0.9584881184149462
    w: 0.25681127235414314
vo_state: 1
integrator_state: 3
```

Please notice **x: 5.06**. The algorithm has been running for about 10-20 minutes and the camera has been sitting on the table this entire time. The D435i camera is in a well-lit room, facing to the ceiling, and the IMU hasn't been exposed to any vibrations.  

What might be reason of this drift? Do I need to do anything (calibration, etc.) to maximize the performance of Elbrus? I will use this setup to benchmark the performance of Elbrus against some other open-source VIO/VISLAM algorithms, therefore I must make sure that I'm doing everything I can to get the best performance that I can.
